language: python
sudo: yes

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27-ansible21
    - python: 2.7
      env: TOXENV=py27-ansible20
    - python: 2.7
      env: TOXENV=py27-ansible19

install:
  - pip install tox

script:
  - tox

notifications:
  email: false
  slack:
    template:
      - "%{repository_name}@%{branch} %{commit} : [%{build_number}] %{result} "
      - "%{build_url}"
      - "'%{commit_subject}' by %{author}"
      - "%{elapsed_time} : %{duration}"
      - "%{message}"
    rooms:
      secure: N/NULi+vkMzZHOOjwvf81LGPfrB/KQr6JBfJaIdb1gPd0JSmE4pJJUk772FrpjC0/FG8ncvYyXZb1rhf3hiyTzgMlPN855MP+0sUo2gJEDay0scXsaoMfkO4VEFbAIXrW+XIEp4VVagG3qRLwjxYiC/Q8GT6tuRzwApdGyBPkA3dmM29L/A/ZYwOcXOSoMnBZPXShumnrJXVK2h+eFuja7KIrJBBh1zCAjiQPp92Jcs32JhBH/fTsPIh4kfF/iUxzVcbc5gSyQZ4anYpC7sqB1JQUebB4fHXg2UXLs6KoeV3vhaBfIFBOzkWsgNAl6CXCp3vxRKehJMkyY32wAA5y8NXgdUpKhMpcOpxFZzUYqfgTE/BsEzavG+6o6sEC1gU8cWg94J109thNmNlrBnYPznDXl6RZl+ztIr8FKh6NXIoicgpr9LyecThuJf7wppv0T6d3oU5R/Sa5dU1UTtVHRzf4/mxhjSVUsuMVSooNQq38dnYiu8+HgttZoPPhgT9yHbej4WMRkJy/oLYmscYlXPtKX15FowaBzsp9Q6j5aXvLVJjgzjdJlUgXTwiuu4VmoLJaK0eYa8w9JKkqcDV88CeJRisaOU5PCEU3mKSiEIg/WRWLngqHyKpTsU0dIhrmNXXmlouRJA7n9lLc0Vm8H1HaD3jvM9Ph+ShqhqISjo=
    on_success: always
    on_failure: always
  webhooks: https://galaxy.ansible.com/api/v1/notifications/

before_cache:
  - rm -f ${HOME}/.cache/pip/log/debug.log

cache:
  directories:
    - ${HOME}/.cache/pip

