language: python
dist: trusty
sudo: yes

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27-ansible21
    - python: 2.7
      env: TOXENV=py27-ansible20

install:
  - pip install tox

script:
  - tox

notifications:
  email: false
  slack:
    template:
      - "%{repository_name}@%{branch} %{commit} : [%{build_number}] %{result} "
      - "%{build_url}"
      - "'%{commit_subject}' by %{author}"
      - "%{elapsed_time} : %{duration}"
      - "%{message}"
    rooms:
      secure: UsNysPQO1Rb1xxi47UJEmaGosstOdrtUNzlbPJL0EBlSdiTKVYwF67KithyJh1JxqGqd346bLTGq9t6ENbEwk6B6mNfp6mH5bq6A15vLagyLqSNOOpSsOQloOa2Lm5+kBB3da5XCqyeqQ7PCg1vE152XArBLSoZyx8Tll1tHTxY+ZODchJbo97fosrJ18YLCy4TE6eYL4O4vBEHU+KG8wQ80QMKD2J8BZ8A+kQBkYnGfLUeemYYzgfyMMQbf2AQ0jUF6lM/ekSdOZ7SAkpSKc9gDIqImdtXBQUbopWo9XhdyTFMRxi/+WqArWHhwE0qC/i7zjg6fv0Uq1JZfmTCMyl6g+YIzy4Sl+rvCypJMT/nhhhZeT4lNmsdZacpgt5rXkc96nhh2GVFvOWpfTh6xZs97f6iWY/lmv3xj0WOhHfbnKbKG6/PKUh+vp9OSX/ueN+KTxtkA1f2yD4UHxtokICtnHK7KiU6bnnrHg/lhP0Ry0voQzQ2eQsEZk+p7H/d+NvC/Vxr3na5DaKq5Y9AfiiwjUcwd3E2vWFLifRucKHNwNrwOskuTgAkDYNv4BS64rW6y9jvWN6hRoaDR5EI1dPM/iRxzmKx19z13AHFXStmN1ERguo/VIVQqiGF0KYBdyaF4Z0tgdtCCbygDauuGgHYjSnE6s/GvS3YJMBFGidU=
    on_success: always
    on_failure: always
  webhooks: https://galaxy.ansible.com/api/v1/notifications/

before_cache:
  - rm -f ${HOME}/.cache/pip/log/debug.log

cache:
  directories:
    - ${HOME}/.cache/pip

