language: python
sudo: yes

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27-ansible21
    - python: 2.7
      env: TOXENV=py27-ansible20

install:
  - pip install tox

script:
  - tox

notifications:
  email: false
  slack:
    template:
      - "%{repository_name}@%{branch} %{commit} : [%{build_number}] %{result} "
      - "%{build_url}"
      - "'%{commit_subject}' by %{author}"
      - "%{elapsed_time} : %{duration}"
      - "%{message}"
    rooms:
      secure: bv25Fzs4N6ALgdCjONn5yuXXMsXG91BHQQNSZEQilXtFkg36NI2crCoGAw92pB1DL4APB1ST0bba4Ju0UKZpUmE9cLXBVvflbdgnZKyaxhxmx0N8sPSdYuWCOnStyM6cGhW7MfiF2mPbWDXAHqku1dxEzcYkeUiPT/aRX6FE27E=
    on_success: always
    on_failure: always
  webhooks: https://galaxy.ansible.com/api/v1/notifications/

before_cache:
  - rm -f ${HOME}/.cache/pip/log/debug.log

cache:
  directories:
    - ${HOME}/.cache/pip

