---
# file: wkhtmltopdf/tasks/build.yml
#
# build tasks.
#

- name: build | clone wkhtmltopdf repository
  git:
    repo: git://github.com/{{ wkhtmltopdf_slug }}.git
    dest: "{{ wkhtmltopdf_dir_src }}"
    version: "{{ wkhtmltopdf_version }}"
    recursive: yes
    track_submodules: yes
    depth: 1
  become_user: "{{ wkhtmltopdf_user }}"
  become: yes

- name: build | set repo ownership
  file:
    path="{{ wkhtmltopdf_dir_src }}"
    owner="{{ wkhtmltopdf_user }}"
    group="{{ wkhtmltopdf_user }}"
    state=directory
    recurse=yes
  become: yes
