---
# file: wkhtmltopdf/tasks/debug.yml
#
# debug tasks.
#

- name: debug
  debug:
    var="{{ item }}"
  when: "{{ item }} is defined"
  with_items:
    - wkhtmltopdf_architecture
    - wkhtmltopdf_build
    - wkhtmltopdf_dir_chroot
    - wkhtmltopdf_dir_src
    - wkhtmltopdf_download_url
    - wkhtmltopdf_mm_version
    - wkhtmltopdf_slug
    - wkhtmltopdf_tarball
    - wkhtmltopdf_user
    - wkhtmltopdf_version
