---
# file: wkhtmltopdf/tasks/main.yml
#

- include: debug.yml
  when: debug | default(false)
  tags: debug

- include_vars: "{{ wkhtmltopdf_installation }}.yml"

- include: validation.yml
  tags: validation

- include: "{{ wkhtmltopdf_installation }}/main.yml"
  tags: installation
