---
# file: wkhtmltopdf/tasks/validation.yml
#
# validation tasks.
#

- name: ensure mandatory variables are set
  fail:
    msg="{{ item }} is a mandatory variable"
  when: "{{ item }} is not defined"
  with_items:
    - wkhtmltopdf_installation
    - wkhtmltopdf_mm_version
    - wkhtmltopdf_user
    - wkhtmltopdf_version

- name: ensure wkhtmltopdf_installation is set to a valid value
  fail:
    msg="wkhtmltopdf_installation needs to be set to source or package ({{ wkhtmltopdf_installation }})"
  when: wkhtmltopdf_installation != 'package' and
        wkhtmltopdf_installation != 'source'
