---
# file: wkhtmltopdf/tasks/validation.yml
#
# validation tasks.
#

- name: ensure mandatory variables are set
  fail:
    msg="{{ item }} is a mandatory variable"
  when: "{{ item }} is not defined"
  with_items:
    - wkhtmltopdf_installation
    - wkhtmltopdf_mm_version
    - wkhtmltopdf_user
    - wkhtmltopdf_version

- name: ensure wkhtmltopdf_installation is set to a valid value
  fail:
    msg="wkhtmltopdf_installation needs to be set to source or package ({{ wkhtmltopdf_installation }})"
  when: wkhtmltopdf_installation != 'package' and
        wkhtmltopdf_installation != 'source'

- name: ensure wkhtmltopdf_installation package is possible for wkhtmltopdf_version
  fail:
    msg="wkhtmltopdf_installation package only possible on 0.12.2 and 0.12.1"
  when: wkhtmltopdf_installation == 'package' and
        (wkhtmltopdf_version != '0.12.2' and wkhtmltopdf_version != '0.12.1')

- name: ensure wkhtmltopdf_installation package is possible for distribution version
  fail:
    msg="wkhtmltopdf_installation package only possible on ubuntu/trusty+precise or debian/wheezy"
  when: wkhtmltopdf_installation == 'package' and ansible_distribution_release not in ['precise', 'trusty', 'wheezy' ]
