---
# file: wkhtmltopdf/tasks/source/main.yml
#
# tasks to install wkhtmltopdf using source.
#

- include: debug.yml
  when: debug | default(false)
  tags: debug

- include: validation.yml
  tags: validation

- name: build | is this desired version installed? => task_version_installed
  shell: "test -e {{ wkhtmltopdf_dir_install }}/wkhtmltopdf-{{ wkhtmltopdf_version }}"
  register: task_version_installed
  changed_when: no
  failed_when: no

- name: build | download and install source (using tarball or git)
  include: "{{ wkhtmltopdf_build }}.yml"
  when: (task_version_installed is defined and task_version_installed.rc != 0)

- name: build | setup chroot environment
  shell: "python2.7 scripts/build.py {{ wkhtmltopdf_chroot_args }}"
  when: (task_version_installed is defined and task_version_installed.rc != 0)
  register: task_setup_chroot
  changed_when: not task_setup_chroot.stdout.find('skipped')
  args:
    chdir: "{{ wkhtmltopdf_dir_source_version }}"
  environment:
    WKHTMLTOX_CHROOT: "{{ wkhtmltopdf_dir_chroot }}"
  become: yes

- name: build | build binaries
  shell: "python2.7 scripts/build.py {{ wkhtmltopdf_build_args }}"
  when: (task_version_installed is defined and task_version_installed.rc != 0)
  register: task_build
  changed_when: not task_build.stdout.find('Nothing to be done')
  args:
    chdir: "{{ wkhtmltopdf_dir_source_version }}"
  environment:
    WKHTMLTOX_CHROOT: "{{ wkhtmltopdf_dir_chroot }}"
  become_user: "{{ wkhtmltopdf_user }}"
  become: yes

- name: build | install version specific binaries
  copy:
    src="{{ wkhtmltopdf_dir_source_version }}/static-build/linux-generic-{{ wkhtmltopdf_architecture }}/app/bin/{{ item.src }}"
    dest="{{ wkhtmltopdf_dir_install }}/{{ item.dest }}"
    remote_src=yes
    owner=root
    group=root
    mode=0755
  become: yes
  when: (task_version_installed is defined and task_version_installed.rc != 0)
  with_items:
    - { src: 'wkhtmltoimage', dest: "wkhtmltoimage-{{ wkhtmltopdf_version }}" }
    - { src: 'wkhtmltopdf', dest: "wkhtmltopdf-{{ wkhtmltopdf_version }}" }
    - { src: "libwkhtmltox.so.{{ wkhtmltopdf_version }}", dest: "libwkhtmltox.so.{{ wkhtmltopdf_version }}" }

- name: build | create default version symlinks
  file:
    src="{{ wkhtmltopdf_dir_install }}/{{ item.src }}"
    dest="{{ wkhtmltopdf_dir_install }}/{{ item.dest }}"
    owner=root
    group=root
    state=link
  become: yes
  when: wkhtmltopdf_default_version
  with_items:
    - { src: "wkhtmltopdf-{{ wkhtmltopdf_version }}", dest: 'wkhtmltopdf' }
    - { src: "wkhtmltoimage-{{ wkhtmltopdf_version }}", dest: 'wkhtmltoimage' }
    - { src: "libwkhtmltox.so.{{ wkhtmltopdf_version }}", dest: 'libwkhtmltox.so' }
