---
# file: wkhtmltopdf/tasks/source/main.yml
#
# tasks to install wkhtmltopdf using source.
#

- include: debug.yml
  when: debug | default(false)
  tags: debug

- include: validation.yml
  tags: validation

- name: build | install build dependencies
  action: "{{ ansible_pkg_mgr }} name={{ item }} state=present"
  with_items:
    - "{{ wkhtmltopdf_build_dependencies }}"
  become: yes

- include: "{{ wkhtmltopdf_build }}.yml"

- name: build | setup chroot environment
  shell: "scripts/build.py {{ wkhtmltopdf_chroot_args }}"
  register: task_setup_chroot
  changed_when: not task_setup_chroot.stdout.find('skipped')
  args:
    chdir: "{{ wkhtmltopdf_dir_source_version }}"
  environment:
    WKHTMLTOX_CHROOT: "{{ wkhtmltopdf_dir_chroot }}"
  become: yes

- name: build | build binaries
  shell: "scripts/build.py { wkhtmltopdf_build_args }}"
  register: task_build
  changed_when: not task_build.stdout.find('Nothing to be done')
  args:
    chdir: "{{ wkhtmltopdf_dir_source_version }}"
  environment:
    WKHTMLTOX_CHROOT: "{{ wkhtmltopdf_dir_chroot }}"
  become_user: "{{ wkhtmltopdf_user }}"
  become: yes

- name: build | copy binaries
  copy:
    src="{{ wkhtmltopdf_dir_source_version }}/static-build/linux-generic-{{ wkhtmltopdf_architecture }}/app/bin/{{ item }}"
    dest="{{ wkhtmltopdf_dir_install }}"
    remote_src=yes
    owner=root
    group=root
    mode=0755
  become: yes
  with_items:
    - wkhtmltoimage
    - wkhtmltopdf
    - "libwkhtmltox.so.{{ wkhtmltopdf_version }}"
  become: yes

- name: build | create symlinks
  file:
    src="{{ wkhtmltopdf_dir_install }}/{{ item.src }}"
    dest="{{ wkhtmltopdf_dir_install }}/{{ item.dest }}"
    owner=root
    group=root
    state=link
  become: yes
  with_items:
    - { src: "libwkhtmltox.so.{{ wkhtmltopdf_version }}", dest: "libwkhtmltox.so.{{ wkhtmltopdf_version.split('.')[0] }}" }
    - { src: "libwkhtmltox.so.{{ wkhtmltopdf_version }}", dest: "libwkhtmltox.so.{{ '.'.join(wkhtmltopdf_version.split('.')[0:2]) }}" }
    - { src: 'wkhtmltopdf', dest: "wkhtmltopdf-{{ wkhtmltopdf_version }}" }
    - { src: 'wkhtmltoimage', dest: "wkhtmltoimage-{{ wkhtmltopdf_version }}" }
