---
# file: wkhtmltopdf/tasks/build/validation.yml
#
# validation tasks.
#

- name: build | ensure build mandatory variables are set
  fail:
    msg="{{ item }} is a mandatory variable"
  when: "{{ item }} is not defined"
  with_items:
    - wkhtmltopdf_architecture
    - wkhtmltopdf_build
    - wkhtmltopdf_build_args
    - wkhtmltopdf_chroot_args
    - wkhtmltopdf_dir_chroot
    - wkhtmltopdf_dir_install
    - wkhtmltopdf_dir_source
    - wkhtmltopdf_dir_source_version
    - wkhtmltopdf_force_build
    - wkhtmltopdf_slug
    - wkhtmltopdf_tarball
    - wkhtmltopdf_tarball_download_url
