---
# file: wkhtmltopdf/tasks/package/validation.yml
#
# validation tasks.
#

- name: package | ensure wkhtmltopdf_installation package is possible for wkhtmltopdf_version
  fail:
    msg="wkhtmltopdf_installation package only possible on 0.12.2 and 0.12.1"
  when: wkhtmltopdf_version != '0.12.2' and wkhtmltopdf_version != '0.12.1'

- name: package | ensure wkhtmltopdf_installation package is possible for distribution version
  fail:
    msg="wkhtmltopdf_installation package only possible on ubuntu/trusty+precise or debian/wheezy"
  when: wkhtmltopdf_installation == 'package' and ansible_distribution_release not in ['precise', 'trusty', 'wheezy' ]

- name: build | ensure build mandatory variables are set
  fail:
    msg="{{ item }} is a mandatory variable"
  when: "{{ item }} is not defined"
  with_items:
    - wkhtmltopdf_package
    - wkhtmltopdf_package_download_url
